# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2024
customText = """Site Total Visitors: <span id='vercount_value_site_uv'>Loading</span><br/>
      Total Visits: <span id='vercount_value_site_pv'>Loading</span>"""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
subtitle = "Welcome to my blog where I share my thoughts, experiences, and insights on photography and technology. æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ï¼Œåœ¨è¿™é‡Œæˆ‘åˆ†äº«å…³äºæ‘„å½±å’ŒæŠ€æœ¯çš„æƒ³æ³•ã€ç»å†å’Œè§è§£ã€‚"
emoji = "ğŸ“·"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed by junevision / å…­æœˆé›¨June"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "junevision/junevision.github.io"
repoID = "R_kgDOO0Jf8w"
category = "General"
categoryID = "DIC_kwDOO0Jf884Cr6hN"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 0
